### ISSUE TITLE
Incorrect color on distro support subpage

### ISSUE THREAD

**Issue by Paradigm0001** [bedrocklinux/bedrocklinux-website#28]
https://bedrocklinux.org/0.7/distro-support.html
This page has incorrect coloring for the fetchability of CRUX

Illustrated in this crude image:
![image](https://user-images.githubusercontent.com/46477191/58142264-e8103d00-7c35-11e9-8706-663d99ee58fa.png)

**Comment by paradigm** [comment]
Good eye!  Should now be fixed, thanks for bringing it to my attention.
