### ISSUE TITLE
Favicon?

### ISSUE THREAD

**Issue by Bobbbay** [bedrocklinux/bedrocklinux-website#39]
Every website needs a favicon, and I've noticed this one doesn't :)

Even a simple thing like 
![Frame 1 (5)](https://user-images.githubusercontent.com/49123594/89684465-7e2a9480-d8c8-11ea-9b44-aa7c0af3cd1c.png)
Will do :)

Cheers!

**Comment by paradigm** [comment]
I made a PR.  Please review.

Much like HTML/CSS, regarding image manipulation:

- My skill set is _just_ enough to get by and I expect others can do much better.
- I'm very picky.

I take no issue with complaints that the image I made is inadequate here, but I do ask anyone kind enough to offer his/her skill set to exercise some patience in appeasing my preferences.

**Comment by Bobbbay** [comment]
The image is fine imo :)

**Comment by paradigm** [comment]
Excellent, thanks :)
